# ELLIS Machine Learning for Molecules Discovery workshop
remote_theme: tuur29/pages-themes-cayman
title: ML for molecules and materials in the era of LLMs [ML4Molecules]
description: ELLIS workshop, HYBRID, December 6, 2024
color:
    gradient_left: "#333333"
    gradient_right: "#333333" # "#686868"
    header: "#c0c0c0"
    android_theme: "#000" # this default to gradient_color
    link: "#6a9bdd" # this default to gradient_color
    section_title: "#e38e48" # this default to gradient_color
buttons:
    github_hide: true # hides "View on Github"
