# ELLIS Machine Learning for Molecules Discovery workshop
remote_theme: tuur29/pages-themes-cayman
title: Generative Models, LLMs, and the Future of Molecular AI [ML4Molecules 2025]
description: ELLIS Unconference workshop, Copenhagen, December 2, 2025
color:
    gradient_left: "#333333"
    gradient_right: "#333333" # "#686868"
    header: "#c0c0c0"
    android_theme: "#000" # this default to gradient_color
    link: "#6a9bdd" # this default to gradient_color
    section_title: "#e38e48" # this default to gradient_color
buttons:
    github_hide: true # hides "View on Github"
